<?php

// PRODUCTOS POR COLORES 

$SQL_PRODUCTOS = "SELECT * FROM DET_COLOR AS E 
INNER JOIN MARCAS AS B ON E.FK_Marca = B.PK_Marca  
INNER JOIN CATEGORIAS AS C ON E.FK_Categoria = C.PK_Categoria 
INNER JOIN ESTADOS AS D ON E.FK_Estado = D.PK_Estado
INNER JOIN COLORES AS F ON F.PK_Color = E.FK_Color
INNER JOIN ETIQUETA AS G ON G.PK_Etiqueta = E.FK_Etiqueta
WHERE E.FK_Estado <>  '3'"; // ELIMINADO
$DATOS_PRODUCTOS = $conexion->query($SQL_PRODUCTOS);


$SQL_COLORES = "SELECT * FROM COLORES AS A  WHERE A.FK_Estado NOT IN ('2','3')";
$DATOS_COLORES = $conexion->query($SQL_COLORES);

$SQL_MARCAS = "SELECT * FROM MARCAS AS B WHERE B.FK_Estado NOT IN ('2','3')";
$DATOS_MARCAS = $conexion->query($SQL_MARCAS);

$SQL_ETIQUETAS = "SELECT * FROM ETIQUETA AS C  WHERE C.FK_Estado NOT IN ('2','3')";
$DATOS_ETIQUETAS = $conexion->query($SQL_ETIQUETAS);


$SQL_MODELOS = "SELECT * FROM PRODUCTOS AS A INNER JOIN MARCAS AS B ON A.FK_Marca = B.PK_Marca  INNER JOIN CATEGORIAS AS C ON A.FK_Categoria = C.PK_Categoria INNER JOIN ESTADOS AS D ON A.FK_Estado = D.PK_Estado
WHERE A.FK_Estado NOT IN ('2','3')";
$DATOS_MODELOS = $conexion->query($SQL_MODELOS);



$SQL_TALLAS = "SELECT * FROM TALLAS AS G  WHERE G.FK_Estado NOT IN ('2','3')";
$DATOS_TALLAS = $conexion->query($SQL_TALLAS);
